version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env